"""
Alert models for early warning system
Tracks alerts, notifications, and acknowledgments
"""

from sqlalchemy import Column, Integer, String, Float, ForeignKey, Enum as SQLEnum
from sqlalchemy.orm import relationship
import enum

from app.models import BaseModel


class AlertSeverity(str, enum.Enum):
    """Alert severity levels - color coded"""
    GREEN = "green"         # Advisory - Be aware
    YELLOW = "yellow"       # Watch - Be prepared
    ORANGE = "orange"       # Warning - Take action
    RED = "red"             # Extreme - Evacuate now


class AlertStatus(str, enum.Enum):
    """Alert lifecycle status"""
    PENDING = "pending"             # Generated, not yet dispatched
    DISPATCHED = "dispatched"       # Sent to notification services
    ACTIVE = "active"               # Live ongoing warning
    ACKNOWLEDGED = "acknowledged"   # Received by officials
    IN_PROGRESS = "in_progress"     # Action being taken
    RESOLVED = "resolved"           # Threat passed
    CANCELLED = "cancelled"         # False alarm
    EXPIRED = "expired"             # Time window passed


class Alert(BaseModel):
    """
    Flash flood / landslide alert
    Generated by prediction engine, dispatched to officials and public
    """

    __tablename__ = "alerts"

    # Location
    region_id = Column(Integer, ForeignKey("regions.id"), nullable=False, index=True)
    region = relationship("Region", back_populates="alerts")

    # Alert Details
    alert_code = Column(String(50), unique=True, index=True)  # e.g., "UKD-CHM-20260916-001"
    title = Column(String(255), nullable=False)
    description = Column(String(1000), nullable=False)

    # Severity & Type
    severity = Column(SQLEnum(AlertSeverity), nullable=False, index=True)
    alert_type = Column(String(50), nullable=False)  # "flash_flood", "landslide", "combined"

    # Risk Data
    risk_score = Column(Float, nullable=False)
    confidence = Column(Float, nullable=False)

    # Timing
    issued_at = Column(String(50), nullable=False)  # ISO datetime when alert was issued
    effective_at = Column(String(50), nullable=True)  # When threat begins
    expires_at = Column(String(50), nullable=True)  # When alert expires
    lead_time_hours = Column(Float, nullable=True)

    # Status
    status = Column(SQLEnum(AlertStatus), default=AlertStatus.PENDING, index=True)
    acknowledged_at = Column(String(50), nullable=True)
    acknowledged_by = Column(String(255), nullable=True)
    resolved_at = Column(String(50), nullable=True)

    # Impact Assessment
    affected_population = Column(Integer, default=0)
    affected_villages = Column(String(500), nullable=True)  # JSON list
    evacuation_required = Column(Integer, default=0)  # boolean

    # Actionable Information
    recommended_actions = Column(String(1000), nullable=True)  # JSON list
    evacuation_routes = Column(String(1000), nullable=True)  # JSON list of route IDs
    safe_zones = Column(String(500), nullable=True)  # JSON list of coordinates

    # Notifications
    sms_sent = Column(Integer, default=0)  # boolean
    sms_count = Column(Integer, default=0)
    push_sent = Column(Integer, default=0)  # boolean
    push_count = Column(Integer, default=0)
    email_sent = Column(Integer, default=0)  # boolean
    email_count = Column(Integer, default=0)
    siren_triggered = Column(Integer, default=0)  # boolean

    # Source
    triggered_by = Column(String(100), default="ml_engine")  # "ml_engine", "manual", "sensor_threshold"
    model_version = Column(String(50), nullable=True)
    source_sensors = Column(String(500), nullable=True)  # JSON list of sensor IDs

    # Escalation
    escalation_level = Column(Integer, default=1)  # 1, 2, 3...
    escalated_at = Column(String(50), nullable=True)

    # Feedback
    was_accurate = Column(Integer, nullable=True)  # boolean - post-event evaluation
    false_alarm = Column(Integer, default=0)  # boolean
    feedback_notes = Column(String(500), nullable=True)

    def __repr__(self):
        return f"<Alert(id={self.id}, code='{self.alert_code}', severity='{self.severity}', status='{self.status}')>"
